# Generated by Django 4.1 on 2024-03-28 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='user',
            new_name='author',
        ),
    ]
