# Generated by Django 5.0.4 on 2024-04-09 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0004_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='detail',
        ),
    ]
