# Generated by Django 5.0.4 on 2024-04-19 20:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='company_logo')),
                ('owner', models.CharField(max_length=50)),
                ('owner_image', models.ImageField(upload_to='company_logo')),
                ('co_owner', models.CharField(blank=True, max_length=50, null=True)),
                ('co_owner_image', models.ImageField(upload_to='company_logo')),
                ('headquater', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.FloatField()),
                ('staff', models.IntegerField()),
                ('instagram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
