# Generated by Django 4.1 on 2024-03-28 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.FloatField()),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70)),
                ('email', models.CharField(blank=True, max_length=130, null=True)),
                ('number', models.IntegerField()),
                ('address_1', models.CharField(max_length=130)),
                ('address_2', models.CharField(max_length=130)),
                ('city', models.CharField(max_length=130)),
                ('state', models.CharField(max_length=130)),
                ('country', models.CharField(max_length=130)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Shipping Address',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('price', models.FloatField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('coupon', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Failed', 'Failed'), ('Review', 'Review'), ('Approved', 'Approved')], default='Pending', max_length=10)),
                ('bank_name', models.CharField(blank=True, default='Zenith Bank', max_length=100, null=True)),
                ('acct_no', models.IntegerField(blank=True, default='2212833276', null=True)),
                ('acct_name', models.CharField(blank=True, default='VICTOR KENNETH', max_length=100, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.shippingaddress')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.shippingaddress'),
        ),
    ]
