# Generated by Django 5.0.4 on 2024-04-29 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
